version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: DockerfileSQL
    container_name: mysql-sublimapp
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sublimapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  jetty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jetty-sublimapp
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
    links:
      - mysql

volumes:
  mysql_data:
