version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: DockerfileSQL
    container_name: mysql-sublimapp
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sublimapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-puser"]
      interval: 10s
      timeout: 5s
      retries: 5


  jetty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jetty-sublimapp
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
    links:
      - mysql

volumes:
  mysql_data:

#1 hacer docker-compose down --volumes --remove-orphans
#2 hacer mvn clean package
#3 hacer docker-compose up --build
